const path = require('path')
const fs=require('fs')

// const result = path.resolve("class-03","index.js")
// console.log(result)


// tasks for FS and path


// Task 1

const filepath= path.join("documents","invoice.pdf");
fs.writeFileSync("__dirname", "invoice Generated sucessfully");


console.log(path.basename(filepath ));

// Task 2 Using the same filePath, print: 1. Folder path 2. File extension

  ;
console.log(path.dirname(filepath));

 
console.log(path.extname(filepath) );

// task 3 create folder named Invoices and a file inside it named invoices.txt

// fs.mkdirSync("invoices");
const pathfile=path.join("invoices","invoices.txt")
fs.writeFileSync(pathfile,"Invoice generated by node.js")

console.log(fs.readFileSync(pathfile,"utf-8"))